// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	slurm "github.com/deepsquare-io/the-grid/supervisor/pkg/slurm"
	mock "github.com/stretchr/testify/mock"
)

// JobScheduler is an autogenerated mock type for the JobScheduler type
type JobScheduler struct {
	mock.Mock
}

// Submit provides a mock function with given fields: req
func (_m *JobScheduler) Submit(req *slurm.SubmitJobRequest) (int, error) {
	ret := _m.Called(req)

	var r0 int
	if rf, ok := ret.Get(0).(func(*slurm.SubmitJobRequest) int); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*slurm.SubmitJobRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJobScheduler interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobScheduler creates a new instance of JobScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobScheduler(t mockConstructorTestingTNewJobScheduler) *JobScheduler {
	mock := &JobScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
