// Code generated by mockery v2.32.4. DO NOT EDIT.

package mockjob

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MetaScheduledIdsFetcher is an autogenerated mock type for the MetaScheduledIdsFetcher type
type MetaScheduledIdsFetcher struct {
	mock.Mock
}

type MetaScheduledIdsFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MetaScheduledIdsFetcher) EXPECT() *MetaScheduledIdsFetcher_Expecter {
	return &MetaScheduledIdsFetcher_Expecter{mock: &_m.Mock}
}

// GetMetaScheduledJobIDs provides a mock function with given fields: ctx
func (_m *MetaScheduledIdsFetcher) GetMetaScheduledJobIDs(ctx context.Context) ([][32]byte, error) {
	ret := _m.Called(ctx)

	var r0 [][32]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([][32]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) [][32]byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][32]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetaScheduledJobIDs'
type MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call struct {
	*mock.Call
}

// GetMetaScheduledJobIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MetaScheduledIdsFetcher_Expecter) GetMetaScheduledJobIDs(ctx interface{}) *MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call {
	return &MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call{Call: _e.mock.On("GetMetaScheduledJobIDs", ctx)}
}

func (_c *MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call) Run(run func(ctx context.Context)) *MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call) Return(_a0 [][32]byte, _a1 error) *MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call) RunAndReturn(run func(context.Context) ([][32]byte, error)) *MetaScheduledIdsFetcher_GetMetaScheduledJobIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetaScheduledIdsFetcher creates a new instance of MetaScheduledIdsFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetaScheduledIdsFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetaScheduledIdsFetcher {
	mock := &MetaScheduledIdsFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
