with-expecter: true
filename: '{{.InterfaceName}}_mock.go'
dir: 'mocks/mock{{.PackageName}}'
mockname: '{{.InterfaceName}}'
outpkg: 'mock{{.PackageName}}'
packages:
  github.com/deepsquare-io/grid/cli/types/job:
    interfaces:
      MetaScheduledIdsFetcher:
      Fetcher:
