apiVersion: v1
kind: Pod
metadata:
  name: sbatch-service
  labels:
    name: sbatch-service
spec:
  containers:
    - name: redis
      image: registry-1.docker.io/library/redis:latest
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 6379
    - name: sbatch-service
      image: localhost/sbatch-service:latest
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 3000
          hostPort: 3000
      env:
        - name: LISTEN_ADDRESS
          value: ':3000'
        - name: REDIS_ADDRESS
          value: 'redis://localhost:6379/0'
        - name: LOGGER_ENDPOINT
          value: logger.example.com:443
        - name: DEBUG
          value: 'true'
