// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocksecret

import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *Manager) Get() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// Manager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Manager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *Manager_Expecter) Get() *Manager_Get_Call {
	return &Manager_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *Manager_Get_Call) Run(run func()) *Manager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Manager_Get_Call) Return(_a0 []byte) *Manager_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_Get_Call) RunAndReturn(run func() []byte) *Manager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: _a0
func (_m *Manager) Validate(_a0 []byte) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Manager_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type Manager_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - _a0 []byte
func (_e *Manager_Expecter) Validate(_a0 interface{}) *Manager_Validate_Call {
	return &Manager_Validate_Call{Call: _e.mock.On("Validate", _a0)}
}

func (_c *Manager_Validate_Call) Run(run func(_a0 []byte)) *Manager_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *Manager_Validate_Call) Return(_a0 bool) *Manager_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_Validate_Call) RunAndReturn(run func([]byte) bool) *Manager_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
