// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	supervisorv1alpha1 "github.com/deepsquare-io/the-grid/supervisor/gen/go/supervisor/v1alpha1"
)

// JobAPIClient is an autogenerated mock type for the JobAPIClient type
type JobAPIClient struct {
	mock.Mock
}

// SetJobStatus provides a mock function with given fields: ctx, in, opts
func (_m *JobAPIClient) SetJobStatus(ctx context.Context, in *supervisorv1alpha1.SetJobStatusRequest, opts ...grpc.CallOption) (*supervisorv1alpha1.SetJobStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *supervisorv1alpha1.SetJobStatusResponse
	if rf, ok := ret.Get(0).(func(context.Context, *supervisorv1alpha1.SetJobStatusRequest, ...grpc.CallOption) *supervisorv1alpha1.SetJobStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*supervisorv1alpha1.SetJobStatusResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *supervisorv1alpha1.SetJobStatusRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJobAPIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobAPIClient creates a new instance of JobAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobAPIClient(t mockConstructorTestingTNewJobAPIClient) *JobAPIClient {
	mock := &JobAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
