// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// JobBatchFetcher is an autogenerated mock type for the JobBatchFetcher type
type JobBatchFetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, hash
func (_m *JobBatchFetcher) Fetch(ctx context.Context, hash string) (string, error) {
	ret := _m.Called(ctx, hash)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJobBatchFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobBatchFetcher creates a new instance of JobBatchFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobBatchFetcher(t mockConstructorTestingTNewJobBatchFetcher) *JobBatchFetcher {
	mock := &JobBatchFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
