// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"

	metascheduler "github.com/deepsquare-io/the-grid/supervisor/pkg/metascheduler"

	mock "github.com/stretchr/testify/mock"
)

// JobHandler is an autogenerated mock type for the JobHandler type
type JobHandler struct {
	mock.Mock
}

// SetJobStatus provides a mock function with given fields: ctx, jobID, jobStatus, jobDuration
func (_m *JobHandler) SetJobStatus(ctx context.Context, jobID [32]byte, jobStatus metascheduler.JobStatus, jobDuration uint64) error {
	ret := _m.Called(ctx, jobID, jobStatus, jobDuration)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, [32]byte, metascheduler.JobStatus, uint64) error); ok {
		r0 = rf(ctx, jobID, jobStatus, jobDuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewJobHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobHandler creates a new instance of JobHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobHandler(t mockConstructorTestingTNewJobHandler) *JobHandler {
	mock := &JobHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
