// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/ethereum/go-ethereum/event"

	metascheduler "github.com/deepsquare-io/the-grid/supervisor/gen/go/contracts/metascheduler"

	mock "github.com/stretchr/testify/mock"
)

// JobMetaQueue is an autogenerated mock type for the JobMetaQueue type
type JobMetaQueue struct {
	mock.Mock
}

// Claim provides a mock function with given fields: ctx
func (_m *JobMetaQueue) Claim(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefuseJob provides a mock function with given fields: ctx, jobID
func (_m *JobMetaQueue) RefuseJob(ctx context.Context, jobID [32]byte) error {
	ret := _m.Called(ctx, jobID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, [32]byte) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WatchClaimNextJobEvent provides a mock function with given fields: ctx, sink
func (_m *JobMetaQueue) WatchClaimNextJobEvent(ctx context.Context, sink chan<- *metascheduler.MetaSchedulerClaimNextJobEvent) (event.Subscription, error) {
	ret := _m.Called(ctx, sink)

	var r0 event.Subscription
	if rf, ok := ret.Get(0).(func(context.Context, chan<- *metascheduler.MetaSchedulerClaimNextJobEvent) event.Subscription); ok {
		r0 = rf(ctx, sink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(event.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, chan<- *metascheduler.MetaSchedulerClaimNextJobEvent) error); ok {
		r1 = rf(ctx, sink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJobMetaQueue interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobMetaQueue creates a new instance of JobMetaQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobMetaQueue(t mockConstructorTestingTNewJobMetaQueue) *JobMetaQueue {
	mock := &JobMetaQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
