// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/ethereum/go-ethereum/event"
	mock "github.com/stretchr/testify/mock"
)

// ResubscribeErrFunc is an autogenerated mock type for the ResubscribeErrFunc type
type ResubscribeErrFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ResubscribeErrFunc) Execute(_a0 context.Context, _a1 error) (event.Subscription, error) {
	ret := _m.Called(_a0, _a1)

	var r0 event.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, error) (event.Subscription, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, error) event.Subscription); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(event.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, error) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewResubscribeErrFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewResubscribeErrFunc creates a new instance of ResubscribeErrFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResubscribeErrFunc(t mockConstructorTestingTNewResubscribeErrFunc) *ResubscribeErrFunc {
	mock := &ResubscribeErrFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
