// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	sbatchapiv1alpha1 "github.com/deepsquare-io/the-grid/supervisor/gen/go/sbatchapi/v1alpha1"
)

// SBatchAPIClient is an autogenerated mock type for the SBatchAPIClient type
type SBatchAPIClient struct {
	mock.Mock
}

// GetSBatch provides a mock function with given fields: ctx, in, opts
func (_m *SBatchAPIClient) GetSBatch(ctx context.Context, in *sbatchapiv1alpha1.GetSBatchRequest, opts ...grpc.CallOption) (*sbatchapiv1alpha1.GetSBatchResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *sbatchapiv1alpha1.GetSBatchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sbatchapiv1alpha1.GetSBatchRequest, ...grpc.CallOption) (*sbatchapiv1alpha1.GetSBatchResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sbatchapiv1alpha1.GetSBatchRequest, ...grpc.CallOption) *sbatchapiv1alpha1.GetSBatchResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sbatchapiv1alpha1.GetSBatchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sbatchapiv1alpha1.GetSBatchRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSBatchAPIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewSBatchAPIClient creates a new instance of SBatchAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSBatchAPIClient(t mockConstructorTestingTNewSBatchAPIClient) *SBatchAPIClient {
	mock := &SBatchAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
