// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeSshAPIServer is an autogenerated mock type for the UnsafeSshAPIServer type
type UnsafeSshAPIServer struct {
	mock.Mock
}

// mustEmbedUnimplementedSshAPIServer provides a mock function with given fields:
func (_m *UnsafeSshAPIServer) mustEmbedUnimplementedSshAPIServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeSshAPIServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeSshAPIServer creates a new instance of UnsafeSshAPIServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeSshAPIServer(t mockConstructorTestingTNewUnsafeSshAPIServer) *UnsafeSshAPIServer {
	mock := &UnsafeSshAPIServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
