with-expecter: true
filename: '{{.InterfaceName}}_mock.go'
dir: 'mocks/mock{{.PackageName}}'
mockname: '{{.InterfaceName}}'
outpkg: 'mock{{.PackageName}}'
packages:
  github.com/deepsquare-io/grid/supervisor/pkg/job/scheduler:
    interfaces:
      Executor:
      Scheduler:
  github.com/deepsquare-io/grid/supervisor/pkg/sbatch:
    interfaces:
      Client:
  github.com/deepsquare-io/grid/supervisor/pkg/metascheduler:
    interfaces:
      MetaScheduler:
  github.com/deepsquare-io/grid/supervisor/pkg/benchmark:
    interfaces:
      Launcher:
  github.com/deepsquare-io/grid/supervisor/pkg/benchmark/secret:
    interfaces:
      Manager:
  github.com/deepsquare-io/grid/supervisor/generated/grpc/health/v1:
    interfaces:
      Health_WatchServer:
  github.com/deepsquare-io/grid/supervisor/generated/logger/v1alpha1:
    interfaces:
      LoggerAPI_WriteClient:
  github.com/deepsquare-io/grid/supervisor/pkg/gridlogger:
    interfaces:
      Dialer:
  github.com/ethereum/go-ethereum/accounts/abi/bind:
    interfaces:
      ContractBackend:
      DeployBackend:
  github.com/ethereum/go-ethereum:
    interfaces:
      Subscription:
