// Code generated by mockery v2.32.4. DO NOT EDIT.

package mockloggerv1alpha1

import (
	context "context"

	loggerv1alpha1 "github.com/deepsquare-io/grid/supervisor/generated/logger/v1alpha1"
	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"
)

// LoggerAPI_WriteClient is an autogenerated mock type for the LoggerAPI_WriteClient type
type LoggerAPI_WriteClient struct {
	mock.Mock
}

type LoggerAPI_WriteClient_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggerAPI_WriteClient) EXPECT() *LoggerAPI_WriteClient_Expecter {
	return &LoggerAPI_WriteClient_Expecter{mock: &_m.Mock}
}

// CloseAndRecv provides a mock function with given fields:
func (_m *LoggerAPI_WriteClient) CloseAndRecv() (*loggerv1alpha1.WriteResponse, error) {
	ret := _m.Called()

	var r0 *loggerv1alpha1.WriteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*loggerv1alpha1.WriteResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *loggerv1alpha1.WriteResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loggerv1alpha1.WriteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggerAPI_WriteClient_CloseAndRecv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAndRecv'
type LoggerAPI_WriteClient_CloseAndRecv_Call struct {
	*mock.Call
}

// CloseAndRecv is a helper method to define mock.On call
func (_e *LoggerAPI_WriteClient_Expecter) CloseAndRecv() *LoggerAPI_WriteClient_CloseAndRecv_Call {
	return &LoggerAPI_WriteClient_CloseAndRecv_Call{Call: _e.mock.On("CloseAndRecv")}
}

func (_c *LoggerAPI_WriteClient_CloseAndRecv_Call) Run(run func()) *LoggerAPI_WriteClient_CloseAndRecv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_CloseAndRecv_Call) Return(_a0 *loggerv1alpha1.WriteResponse, _a1 error) *LoggerAPI_WriteClient_CloseAndRecv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoggerAPI_WriteClient_CloseAndRecv_Call) RunAndReturn(run func() (*loggerv1alpha1.WriteResponse, error)) *LoggerAPI_WriteClient_CloseAndRecv_Call {
	_c.Call.Return(run)
	return _c
}

// CloseSend provides a mock function with given fields:
func (_m *LoggerAPI_WriteClient) CloseSend() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoggerAPI_WriteClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type LoggerAPI_WriteClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *LoggerAPI_WriteClient_Expecter) CloseSend() *LoggerAPI_WriteClient_CloseSend_Call {
	return &LoggerAPI_WriteClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *LoggerAPI_WriteClient_CloseSend_Call) Run(run func()) *LoggerAPI_WriteClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_CloseSend_Call) Return(_a0 error) *LoggerAPI_WriteClient_CloseSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerAPI_WriteClient_CloseSend_Call) RunAndReturn(run func() error) *LoggerAPI_WriteClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with given fields:
func (_m *LoggerAPI_WriteClient) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// LoggerAPI_WriteClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type LoggerAPI_WriteClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *LoggerAPI_WriteClient_Expecter) Context() *LoggerAPI_WriteClient_Context_Call {
	return &LoggerAPI_WriteClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *LoggerAPI_WriteClient_Context_Call) Run(run func()) *LoggerAPI_WriteClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_Context_Call) Return(_a0 context.Context) *LoggerAPI_WriteClient_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerAPI_WriteClient_Context_Call) RunAndReturn(run func() context.Context) *LoggerAPI_WriteClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with given fields:
func (_m *LoggerAPI_WriteClient) Header() (metadata.MD, error) {
	ret := _m.Called()

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoggerAPI_WriteClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type LoggerAPI_WriteClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *LoggerAPI_WriteClient_Expecter) Header() *LoggerAPI_WriteClient_Header_Call {
	return &LoggerAPI_WriteClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *LoggerAPI_WriteClient_Header_Call) Run(run func()) *LoggerAPI_WriteClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_Header_Call) Return(_a0 metadata.MD, _a1 error) *LoggerAPI_WriteClient_Header_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoggerAPI_WriteClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *LoggerAPI_WriteClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *LoggerAPI_WriteClient) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoggerAPI_WriteClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type LoggerAPI_WriteClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *LoggerAPI_WriteClient_Expecter) RecvMsg(m interface{}) *LoggerAPI_WriteClient_RecvMsg_Call {
	return &LoggerAPI_WriteClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *LoggerAPI_WriteClient_RecvMsg_Call) Run(run func(m interface{})) *LoggerAPI_WriteClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_RecvMsg_Call) Return(_a0 error) *LoggerAPI_WriteClient_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerAPI_WriteClient_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *LoggerAPI_WriteClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *LoggerAPI_WriteClient) Send(_a0 *loggerv1alpha1.WriteRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*loggerv1alpha1.WriteRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoggerAPI_WriteClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type LoggerAPI_WriteClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *loggerv1alpha1.WriteRequest
func (_e *LoggerAPI_WriteClient_Expecter) Send(_a0 interface{}) *LoggerAPI_WriteClient_Send_Call {
	return &LoggerAPI_WriteClient_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *LoggerAPI_WriteClient_Send_Call) Run(run func(_a0 *loggerv1alpha1.WriteRequest)) *LoggerAPI_WriteClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*loggerv1alpha1.WriteRequest))
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_Send_Call) Return(_a0 error) *LoggerAPI_WriteClient_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerAPI_WriteClient_Send_Call) RunAndReturn(run func(*loggerv1alpha1.WriteRequest) error) *LoggerAPI_WriteClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *LoggerAPI_WriteClient) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoggerAPI_WriteClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type LoggerAPI_WriteClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *LoggerAPI_WriteClient_Expecter) SendMsg(m interface{}) *LoggerAPI_WriteClient_SendMsg_Call {
	return &LoggerAPI_WriteClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *LoggerAPI_WriteClient_SendMsg_Call) Run(run func(m interface{})) *LoggerAPI_WriteClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_SendMsg_Call) Return(_a0 error) *LoggerAPI_WriteClient_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerAPI_WriteClient_SendMsg_Call) RunAndReturn(run func(interface{}) error) *LoggerAPI_WriteClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with given fields:
func (_m *LoggerAPI_WriteClient) Trailer() metadata.MD {
	ret := _m.Called()

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// LoggerAPI_WriteClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type LoggerAPI_WriteClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *LoggerAPI_WriteClient_Expecter) Trailer() *LoggerAPI_WriteClient_Trailer_Call {
	return &LoggerAPI_WriteClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *LoggerAPI_WriteClient_Trailer_Call) Run(run func()) *LoggerAPI_WriteClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerAPI_WriteClient_Trailer_Call) Return(_a0 metadata.MD) *LoggerAPI_WriteClient_Trailer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerAPI_WriteClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *LoggerAPI_WriteClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoggerAPI_WriteClient creates a new instance of LoggerAPI_WriteClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerAPI_WriteClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerAPI_WriteClient {
	mock := &LoggerAPI_WriteClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
