// Code generated by mockery v2.32.4. DO NOT EDIT.

package mockhealthv1

import (
	context "context"

	healthv1 "github.com/deepsquare-io/the-grid/supervisor/generated/grpc/health/v1"
	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"
)

// Health_WatchServer is an autogenerated mock type for the Health_WatchServer type
type Health_WatchServer struct {
	mock.Mock
}

type Health_WatchServer_Expecter struct {
	mock *mock.Mock
}

func (_m *Health_WatchServer) EXPECT() *Health_WatchServer_Expecter {
	return &Health_WatchServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *Health_WatchServer) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// Health_WatchServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type Health_WatchServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *Health_WatchServer_Expecter) Context() *Health_WatchServer_Context_Call {
	return &Health_WatchServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *Health_WatchServer_Context_Call) Run(run func()) *Health_WatchServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Health_WatchServer_Context_Call) Return(_a0 context.Context) *Health_WatchServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Health_WatchServer_Context_Call) RunAndReturn(run func() context.Context) *Health_WatchServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *Health_WatchServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Health_WatchServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type Health_WatchServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *Health_WatchServer_Expecter) RecvMsg(m interface{}) *Health_WatchServer_RecvMsg_Call {
	return &Health_WatchServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *Health_WatchServer_RecvMsg_Call) Run(run func(m interface{})) *Health_WatchServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Health_WatchServer_RecvMsg_Call) Return(_a0 error) *Health_WatchServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Health_WatchServer_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *Health_WatchServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *Health_WatchServer) Send(_a0 *healthv1.HealthCheckResponse) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*healthv1.HealthCheckResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Health_WatchServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Health_WatchServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *healthv1.HealthCheckResponse
func (_e *Health_WatchServer_Expecter) Send(_a0 interface{}) *Health_WatchServer_Send_Call {
	return &Health_WatchServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *Health_WatchServer_Send_Call) Run(run func(_a0 *healthv1.HealthCheckResponse)) *Health_WatchServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*healthv1.HealthCheckResponse))
	})
	return _c
}

func (_c *Health_WatchServer_Send_Call) Return(_a0 error) *Health_WatchServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Health_WatchServer_Send_Call) RunAndReturn(run func(*healthv1.HealthCheckResponse) error) *Health_WatchServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *Health_WatchServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Health_WatchServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type Health_WatchServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *Health_WatchServer_Expecter) SendHeader(_a0 interface{}) *Health_WatchServer_SendHeader_Call {
	return &Health_WatchServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *Health_WatchServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *Health_WatchServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *Health_WatchServer_SendHeader_Call) Return(_a0 error) *Health_WatchServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Health_WatchServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *Health_WatchServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *Health_WatchServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Health_WatchServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type Health_WatchServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *Health_WatchServer_Expecter) SendMsg(m interface{}) *Health_WatchServer_SendMsg_Call {
	return &Health_WatchServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *Health_WatchServer_SendMsg_Call) Run(run func(m interface{})) *Health_WatchServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Health_WatchServer_SendMsg_Call) Return(_a0 error) *Health_WatchServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Health_WatchServer_SendMsg_Call) RunAndReturn(run func(interface{}) error) *Health_WatchServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *Health_WatchServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Health_WatchServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type Health_WatchServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *Health_WatchServer_Expecter) SetHeader(_a0 interface{}) *Health_WatchServer_SetHeader_Call {
	return &Health_WatchServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *Health_WatchServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *Health_WatchServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *Health_WatchServer_SetHeader_Call) Return(_a0 error) *Health_WatchServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Health_WatchServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *Health_WatchServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *Health_WatchServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// Health_WatchServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type Health_WatchServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *Health_WatchServer_Expecter) SetTrailer(_a0 interface{}) *Health_WatchServer_SetTrailer_Call {
	return &Health_WatchServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *Health_WatchServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *Health_WatchServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *Health_WatchServer_SetTrailer_Call) Return() *Health_WatchServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *Health_WatchServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *Health_WatchServer_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealth_WatchServer creates a new instance of Health_WatchServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealth_WatchServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Health_WatchServer {
	mock := &Health_WatchServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
