on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: sillyangel/releases-to-discord@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
